# Generated by Django 4.1 on 2022-08-31 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0009_rename_data_devolução_emprestimos_data_devolucao'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimos',
            name='avaliacao',
            field=models.CharField(choices=[('P', 'Péssimo '), ('R', 'Ruim'), ('B', 'Bom'), ('O', 'Ótimo')], default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='livros',
            name='emprestado',
            field=models.BooleanField(default=False),
        ),
    ]
